In [1]:
import pandas as pd

In [2]:
baseurl = 'https://hackathon-o.s3-ext.jc.rl.ac.uk/sim-data/analysis/'

In [3]:
relurl = 'syclops/TCat/track_data/5km-RAL3p3/n2560RAL3p3regrid_tracks_20200201-20210111_6h_syclops_psl.csv'
df = pd.read_csv(baseurl + relurl)
df

,track_id,year,month,day,hour,i,j,lon,lat,MSLP,...,LOWTKCC,Z500CC,VO500AVG,RH100MAX,RH850AVG,T850,Z850,ZS,U850DIFF,WS200PMX
0,0,2020,2,1,6,1088,307,153.070312,-61.171875,96486.75,...,-5.25,22.50,-0.000071,0.500,96.22224,272.5625,1021.00,0.0,0.149006,19.85730
1,0,2020,2,1,12,1116,291,157.007812,-62.671875,96332.00,...,-8.25,33.50,-0.000077,0.500,96.75370,272.0625,1006.00,0.0,0.062774,20.20558
2,0,2020,2,1,18,1115,296,156.867188,-62.203125,96254.50,...,-14.50,45.25,-0.000082,0.500,98.57890,271.7812,997.00,0.0,0.149890,18.63548
3,0,2020,2,2,0,1133,283,159.398438,-63.421875,96387.50,...,-3.75,49.50,-0.000070,0.500,97.25176,270.5000,1006.00,0.0,0.078460,17.46783
4,0,2020,2,2,6,1151,301,161.929688,-61.734375,96557.00,...,-6.25,26.75,-0.000085,0.500,98.28259,270.5625,1021.00,0.0,0.251288,16.79890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51333,3310,2021,1,18,18,1224,1388,172.195312,40.171875,97031.75,...,-10.25,8.00,0.000132,0.750,80.03149,281.0625,1105.75,0.0,0.346988,44.47050
51334,3310,2021,1,19,0,1249,1416,175.710937,42.796875,96800.75,...,-19.25,27.25,0.000138,0.625,90.39057,281.6562,1079.50,0.0,0.267357,40.05095
51335,3310,2021,1,19,6,1268,1436,178.382812,44.671875,96605.75,...,-11.00,39.75,0.000122,0.500,88.09457,278.2500,1052.25,0.0,0.262965,36.68319
51336,3310,2021,1,19,12,1283,1443,180.492188,45.328125,96240.75,...,-38.50,42.25,0.000116,0.500,97.45387,277.1562,1016.00,0.0,0.319934,39.70713
51337,3310,2021,1,19,18,1307,1451,183.867188,46.078125,96270.50,...,-27.00,54.75,0.000119,0.500,97.27437,275.3438,1011.50,0.0,0.339398,34.89471

In [4]:
relurl = 'syclops/TCat/track_data/5km-RAL3p3/n2560RAL3p3regrid_tracks_20200201-20201101_6h_tc_psl.csv'
df2 = pd.read_csv(baseurl + relurl)
df2

,track_id,year,month,day,hour,i,j,lon,lat,psl_min,sfcWind_max,orog_max,wind_max_925,wind_max_850,rh_avg_850
0,0,2020,2,5,0,548,814,77.132812,-13.640625,100336.8,16.76166,0.0,19.56080,20.91239,83.36414
1,0,2020,2,5,6,548,811,77.132812,-13.921875,100461.8,16.71124,0.0,24.52805,25.10011,84.10243
2,0,2020,2,5,12,548,809,77.132812,-14.109375,100246.0,18.05936,0.0,24.97780,25.16974,84.56932
3,0,2020,2,5,18,547,806,76.992188,-14.390625,100469.8,15.36636,0.0,22.89685,26.41141,85.59425
4,0,2020,2,6,0,548,807,77.132812,-14.296875,100155.8,18.11767,0.0,25.33093,25.16198,84.94045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2393,101,2020,11,6,12,1816,532,255.445312,-40.078125,100884.5,16.64379,0.0,23.75987,23.38836,89.59305
2394,101,2020,11,6,18,1829,537,257.273438,-39.609375,101015.5,14.85135,0.0,21.19736,21.55697,87.08228
2395,101,2020,11,7,0,1844,538,259.382812,-39.515625,101004.0,13.92502,0.0,19.00863,21.22499,85.55876
2396,101,2020,11,7,6,1853,545,260.648438,-38.859375,101178.2,13.64563,0.0,18.25385,21.47709,87.31368
2397,101,2020,11,7,12,1871,542,263.179688,-39.140625,101210.2,14.50216,0.0,23.76611,20.75602,86.42029